apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: example-voting-app

spec:
  containers:
    - name: db
      image: postgres:9.4
      ports:
        - containerPort: 80
