apiVersion: v1
kind: Service
metadata:
  name: db-service
  
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 5432
  selector:
    name: db-pod
    app: example-voting-app
